[workspace]
members = [
    "osk-core",
    "osk-layout",
    "osk-input",
    "osk-wayland",
    "osk-hyprland",
    "osk-detect",
    "osk-ui",
    "osk-config",
    "osk-ipc",
    "osk-app",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
repository = "https://github.com/smearor/osk-rs"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
notify = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
zbus = "5"
