[workspace]
members = [
    "osk-core",
    "osk-layout",
    "osk-input",
    "osk-wayland",
    "osk-hyprland",
    "osk-detect",
    "osk-ui",
    "osk-config",
    "osk-ipc",
    "osk-app",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
repository = "https://github.com/smearor/osk-rs"

[workspace.dependencies]
cairo-rs = "0.22"
clap = { version = "4", features = ["derive"] }
dirs = "7"
gdk4 = "0.11"
gdk4-wayland = { version = "0.11", features = ["wayland_crate"] }
gio = "0.22"
glib = "0.22"
gtk4 = "0.11"
gtk4-layer-shell = "0.8"
libc = "0.2"
notify = "8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
toml = "1.1"
tracing = "0.1"
tracing-subscriber = "0.3"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
xkbcommon = "0.9"
zbus = "5"
