[package]
name = "osk-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "GTK 4 rendering and touch hit-testing for osk-rs"

[dependencies]
osk-config = { path = "../osk-config" }
osk-core = { path = "../osk-core" }
osk-input = { path = "../osk-input" }
thiserror = { workspace = true }
cairo-rs = { workspace = true }
gdk4 = { workspace = true }
glib = { workspace = true }
gtk4 = { workspace = true }
gtk4-layer-shell = { workspace = true }
tracing = { workspace = true }
